version: '3'

services:
  app:
    build: .
    command: yarn start:dev
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: development
      DATABASE_URL: 'postgresql://postgres:102030@postgres:5432/ecommerce_db?schema=public'
      DB_DIALECT: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 102030
      DB_DBNAME: ecommerce_db
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - .:/app
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'developer@guilhermefalcao.com.br'
      PGADMIN_DEFAULT_PASSWORD: '102030'
    ports:
      - 15432:80
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102030
      POSTGRES_DB: ecommerce_db
networks:
  default:
    name: ecommerce-network
    driver: bridge
